import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Modal,
  Dimensions,
} from "react-native";
import {
  FileText,
  User,
  Calendar,
  CheckCircle,
  Clock,
  AlertCircle,
  X,
  Share,
  Download,
} from "lucide-react-native";
import Markdown from "react-native-markdown-display";
import { Report } from "../types";

interface ReportViewerProps {
  report: Report;
  visible: boolean;
  onClose: () => void;
  onShare?: () => void;
  onDownload?: () => void;
}

export const ReportViewer: React.FC<ReportViewerProps> = ({
  report,
  visible,
  onClose,
  onShare,
  onDownload,
}) => {
  const [activeSection, setActiveSection] = useState<string>("overview");
  const screenWidth = Dimensions.get("window").width;
  const sidebarWidth = Math.min(160, screenWidth * 0.25); // Responsive sidebar width

  const getStatusColor = (status: string) => {
    switch (status) {
      case "Approved":
        return "#10b981";
      case "Reviewed":
        return "#3b82f6";
      case "Generated":
        return "#f59e0b";
      default:
        return "#6b7280";
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "Approved":
        return CheckCircle;
      case "Reviewed":
        return Clock;
      case "Generated":
        return AlertCircle;
      default:
        return FileText;
    }
  };

  const StatusIcon = getStatusIcon(report.status);

  const sections = [
    { id: "overview", label: "Overview", icon: FileText },
    { id: "complaint", label: "Chief Complaint", icon: User },
    { id: "history", label: "History", icon: Calendar },
    { id: "vitals", label: "Vitals", icon: CheckCircle },
    { id: "assessment", label: "Assessment", icon: AlertCircle },
    { id: "plan", label: "Plan", icon: FileText },
    { id: "notes", label: "Notes", icon: FileText },
  ];

  const renderSectionContent = () => {
    const content = report.content;

    switch (activeSection) {
      case "overview":
        return (
          <View style={styles.sectionContent}>
            <View style={styles.overviewGrid}>
              <View style={styles.overviewItem}>
                <Text style={styles.overviewLabel}>Report Type</Text>
                <Text style={styles.overviewValue}>{report.type}</Text>
              </View>
              <View style={styles.overviewItem}>
                <Text style={styles.overviewLabel}>Generated By</Text>
                <Text style={styles.overviewValue}>{report.generatedBy}</Text>
              </View>
              <View style={styles.overviewItem}>
                <Text style={styles.overviewLabel}>Date</Text>
                <Text style={styles.overviewValue}>
                  {new Date(report.date).toLocaleDateString()}
                </Text>
              </View>
              <View style={styles.overviewItem}>
                <Text style={styles.overviewLabel}>Status</Text>
                <View style={styles.statusContainer}>
                  <StatusIcon size={16} color={getStatusColor(report.status)} />
                  <Text
                    style={[
                      styles.overviewValue,
                      { color: getStatusColor(report.status) },
                    ]}
                  >
                    {report.status}
                  </Text>
                </View>
              </View>
            </View>

            {content?.markdown && (
              <View style={styles.markdownPreview}>
                <Text style={styles.sectionTitle}>Full Report Preview</Text>
                <View style={styles.markdownContainer}>
                  <Markdown style={markdownStyles}>
                    {content.markdown.length > 500
                      ? content.markdown.substring(0, 500) + "..."
                      : content.markdown}
                  </Markdown>
                </View>
                <TouchableOpacity
                  style={styles.expandButton}
                  onPress={() => setActiveSection("full")}
                >
                  <Text style={styles.expandButtonText}>View Full Report</Text>
                </TouchableOpacity>
              </View>
            )}
          </View>
        );

      case "complaint":
        return (
          <View style={styles.sectionContent}>
            <Text style={styles.sectionTitle}>Chief Complaint</Text>
            <View style={styles.markdownContainer}>
              <Markdown style={markdownStyles}>
                {content?.chiefComplaint || "No chief complaint recorded"}
              </Markdown>
            </View>
          </View>
        );

      case "history":
        return (
          <View style={styles.sectionContent}>
            <Text style={styles.sectionTitle}>History of Present Illness</Text>
            <View style={styles.markdownContainer}>
              <Markdown style={markdownStyles}>
                {content?.history || "No history recorded"}
              </Markdown>
            </View>
          </View>
        );

      case "vitals":
        return (
          <View style={styles.sectionContent}>
            <Text style={styles.sectionTitle}>Vital Signs Summary</Text>
            <View style={styles.markdownContainer}>
              <Markdown style={markdownStyles}>
                {content?.vitalsSummary || "No vital signs summary available"}
              </Markdown>
            </View>
          </View>
        );

      case "assessment":
        return (
          <View style={styles.sectionContent}>
            <Text style={styles.sectionTitle}>Clinical Assessment</Text>
            <View style={styles.markdownContainer}>
              <Markdown style={markdownStyles}>
                {content?.assessment || "No assessment recorded"}
              </Markdown>
            </View>
          </View>
        );

      case "plan":
        return (
          <View style={styles.sectionContent}>
            <Text style={styles.sectionTitle}>Treatment Plan</Text>
            <View style={styles.markdownContainer}>
              <Markdown style={markdownStyles}>
                {content?.plan || "No treatment plan recorded"}
              </Markdown>
            </View>
          </View>
        );

      case "notes":
        return (
          <View style={styles.sectionContent}>
            <Text style={styles.sectionTitle}>Clinical Notes</Text>
            <View style={styles.markdownContainer}>
              <Markdown style={markdownStyles}>
                {content?.notes || "No additional notes"}
              </Markdown>
            </View>
          </View>
        );

      case "full":
        return (
          <View style={styles.sectionContent}>
            <Text style={styles.sectionTitle}>Complete Report</Text>
            <View style={styles.markdownContainer}>
              <Markdown style={markdownStyles}>
                {content?.markdown || "No full report content available"}
              </Markdown>
            </View>
          </View>
        );

      default:
        return null;
    }
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <View style={styles.container}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.headerLeft}>
            <FileText size={24} color="#1e293b" />
            <View style={styles.headerInfo}>
              <Text style={styles.headerTitle}>{report.title}</Text>
              <Text style={styles.headerSubtitle}>
                {new Date(report.date).toLocaleDateString()}
              </Text>
            </View>
          </View>

          <View style={styles.headerActions}>
            {onShare && (
              <TouchableOpacity style={styles.actionButton} onPress={onShare}>
                <Share size={20} color="#6b7280" />
              </TouchableOpacity>
            )}
            {onDownload && (
              <TouchableOpacity
                style={styles.actionButton}
                onPress={onDownload}
              >
                <Download size={20} color="#6b7280" />
              </TouchableOpacity>
            )}
            <TouchableOpacity style={styles.actionButton} onPress={onClose}>
              <X size={20} color="#6b7280" />
            </TouchableOpacity>
          </View>
        </View>

        <View style={styles.body}>
          {/* Sidebar */}
          <View style={[styles.sidebar, { width: sidebarWidth }]}>
            <ScrollView style={styles.sidebarScroll}>
              {sections.map((section) => {
                const SectionIcon = section.icon;
                const isActive = activeSection === section.id;

                return (
                  <TouchableOpacity
                    key={section.id}
                    style={[
                      styles.sidebarItem,
                      isActive && styles.sidebarItemActive,
                    ]}
                    onPress={() => setActiveSection(section.id)}
                  >
                    <SectionIcon
                      size={18}
                      color={isActive ? "#3b82f6" : "#6b7280"}
                    />
                    <Text
                      style={[
                        styles.sidebarItemText,
                        isActive && styles.sidebarItemTextActive,
                      ]}
                    >
                      {section.label}
                    </Text>
                  </TouchableOpacity>
                );
              })}
            </ScrollView>
          </View>

          {/* Content */}
          <View style={styles.content}>
            <ScrollView style={styles.contentScroll}>
              {renderSectionContent()}
            </ScrollView>
          </View>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  headerInfo: {
    marginLeft: 12,
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1e293b",
  },
  headerSubtitle: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 2,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  actionButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#f1f5f9",
  },
  body: {
    flex: 1,
    flexDirection: "row",
  },
  sidebar: {
    backgroundColor: "white",
    borderRightWidth: 1,
    borderRightColor: "#e2e8f0",
  },
  sidebarScroll: {
    flex: 1,
    padding: 16,
  },
  sidebarItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 4,
  },
  sidebarItemActive: {
    backgroundColor: "#eff6ff",
  },
  sidebarItemText: {
    marginLeft: 12,
    fontSize: 14,
    fontWeight: "500",
    color: "#6b7280",
  },
  sidebarItemTextActive: {
    color: "#3b82f6",
  },
  content: {
    flex: 1,
  },
  contentScroll: {
    flex: 1,
  },
  sectionContent: {
    padding: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1e293b",
    marginBottom: 16,
  },
  contentText: {
    fontSize: 16,
    lineHeight: 24,
    color: "#374151",
  },
  overviewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 24,
  },
  overviewItem: {
    flex: 1,
    minWidth: 150,
    padding: 16,
    backgroundColor: "white",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  overviewLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  overviewValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1e293b",
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  markdownPreview: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  markdownText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#374151",
    marginBottom: 12,
  },
  expandButton: {
    alignSelf: "flex-start",
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#3b82f6",
    borderRadius: 6,
  },
  expandButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "white",
  },
  markdownContainer: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
});

// Markdown styles for better rendering
const markdownStyles = {
  body: {
    fontSize: 16,
    lineHeight: 24,
    color: "#374151",
  },
  heading1: {
    fontSize: 24,
    fontWeight: "700" as const,
    color: "#1e293b",
    marginBottom: 16,
    marginTop: 24,
  },
  heading2: {
    fontSize: 20,
    fontWeight: "600" as const,
    color: "#1e293b",
    marginBottom: 12,
    marginTop: 20,
  },
  heading3: {
    fontSize: 18,
    fontWeight: "600" as const,
    color: "#374151",
    marginBottom: 8,
    marginTop: 16,
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 24,
    color: "#374151",
    marginBottom: 12,
  },
  strong: {
    fontWeight: "600" as const,
    color: "#1e293b",
  },
  em: {
    fontStyle: "italic" as const,
    color: "#4b5563",
  },
  list_item: {
    fontSize: 16,
    lineHeight: 24,
    color: "#374151",
    marginBottom: 4,
  },
  bullet_list: {
    marginBottom: 12,
  },
  ordered_list: {
    marginBottom: 12,
  },
  code_inline: {
    backgroundColor: "#f1f5f9",
    color: "#e11d48",
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
    fontSize: 14,
    fontFamily: "monospace",
  },
  code_block: {
    backgroundColor: "#f8fafc",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginBottom: 12,
  },
  fence: {
    backgroundColor: "#f8fafc",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginBottom: 12,
  },
  blockquote: {
    backgroundColor: "#f8fafc",
    borderLeftWidth: 4,
    borderLeftColor: "#3b82f6",
    paddingLeft: 16,
    paddingVertical: 8,
    marginBottom: 12,
    fontStyle: "italic" as const,
  },
  table: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 8,
    marginBottom: 12,
  },
  thead: {
    backgroundColor: "#f8fafc",
  },
  th: {
    padding: 12,
    fontWeight: "600" as const,
    color: "#1e293b",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  td: {
    padding: 12,
    color: "#374151",
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  hr: {
    backgroundColor: "#e2e8f0",
    height: 1,
    marginVertical: 16,
  },
};
